project:
  type: website

website:
  title: ""
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Why Stats? [textbook]
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

